# Generated by Django 4.1 on 2022-09-22 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_familiares'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesor',
            old_name='correo',
            new_name='email',
        ),
    ]
